extends "res://tests/test_crystal_scene.gd"
## Reuses the real input helpers; this suite exercises held investment gestures.
func run_test() -> void:
	var scene=load("res://scenes/frontier.tscn").instantiate()
	root.add_child(scene)
	await frames(6)
	key(KEY_E,true)
	await frames(8)
	check(scene.sim.context(30).paid==1,"E immediately fills the first campfire slot")
	check(scene.view.investment_progress>0 and scene.view.focus_key=="hall","held E displays progress on its locked target")
	await frames(36)
	check(scene.sim.frontier.city_level==1,"holding E finishes the camp without repeated tapping")
	await frames(50)
	check(scene.sim.pouch.amount==10,"keeping E held does not start another project")
	key(KEY_E,false)
	await frames(3)

	scene.knight.position=Vector2(scene.sim.world.sites.workshop,430)
	await frames(4)
	key(KEY_E,true)
	key(KEY_SPACE,true)
	await frames(3)
	check(scene.sim.pouch.amount==10,"jump and invest pressed together do not pay on takeoff")
	key(KEY_E,false)
	key(KEY_SPACE,false)
	await frames(70)
	var button: Button=scene.hud.interact_button
	var at:=root.get_final_transform()*button.get_global_rect().get_center()
	var event:=InputEventMouseButton.new()
	event.position=at;event.global_position=at;event.button_index=MOUSE_BUTTON_LEFT;event.pressed=true
	Input.parse_input_event(event);Input.flush_buffered_events()
	await frames(8)
	check(scene.sim.context(scene.knight.position.x).paid==1,"holding icon invests immediately before mouse release")
	await frames(70)
	check(scene.sim.world.tools.hammer==1 and scene.sim.pouch.amount==8,"held icon buys exactly one tool")
	event=event.duplicate();event.pressed=false
	Input.parse_input_event(event);Input.flush_buffered_events()
	await frames(3)
	check(not scene.hud.interact_held,"releasing icon clears held input")

	scene.knight.position=Vector2(scene.sim.world.sites.wall,430)
	await frames(4)
	key(KEY_E,true)
	await frames(6)
	var amount: int=scene.sim.pouch.amount
	key(KEY_ESCAPE,true)
	await frames(2)
	key(KEY_ESCAPE,false)
	await frames(40)
	check(scene.paused and scene.sim.pouch.amount==amount,"pause stops held payment before the next crystal")
	key(KEY_ESCAPE,true)
	await frames(2)
	key(KEY_ESCAPE,false)
	await frames(40)
	check(not scene.paused and scene.sim.pouch.amount==amount,"resuming with E still held cannot spend")
	key(KEY_E,false)
	await frames(3)
	key(KEY_E,true)
	await frames(3)
	check(scene.sim.pouch.amount==amount-1,"fresh E resumes the wall's preserved slots")
	key(KEY_SPACE,true)
	await frames(4)
	key(KEY_SPACE,false)
	await frames(70)
	check(not scene.sim.world.wall.pending,"jump cancels remaining held wall payment through landing")
	key(KEY_E,false)
	await frames(3)
	key(KEY_E,true)
	await frames(3)
	key(KEY_E,false)
	check(scene.sim.world.wall.pending,"fresh grounded press finishes the wall order")
	scene.queue_free()
	await process_frame
	print("Investment scene assertions: %d; failures: %d" % [assertions,failures])
	quit(0 if failures==0 else 1)
