extends "res://tests/test_scene.gd"
const Choice=preload("res://application/language_choice.gd")
const Preferences=preload("res://infrastructure/language_preferences.gd")
func run_scene() -> void:
 check(Choice.resolve("auto","zh-Hant-CN")=="zh_TW","script beats territory for Traditional Chinese")
 check(Choice.resolve("auto","zh-Hans-TW")=="zh_CN","explicit Simplified script beats Taiwan territory")
 check(Choice.resolve("auto","zh-HK")=="zh_TW","Hong Kong defaults to Traditional Chinese")
 check(Choice.resolve("auto","fr-FR")=="en","unsupported system language falls back to English")
 check(Choice.resolve("en","zh-TW","schinese")=="en","manual choice beats Steam and system")
 check(Choice.resolve("auto","en-US","tchinese")=="zh_TW","Steam game language takes priority in automatic mode")
 var path="user://test_language_%d.cfg"%Time.get_ticks_usec()
 var service=root.get_node("GameLanguage")
 service.preferences=Preferences.new(path)
 service.choose("zh_TW")
 var menu=load("res://scenes/start_menu.tscn").instantiate();root.add_child(menu);current_scene=menu
 await frames(3)
 check(menu.view.new_button.text=="新遊戲","Traditional title text")
 var selector=menu.view.get_node("%LanguageSelector")
 selector.item_selected.emit(3)
 await frames(3)
 check(menu.view.new_button.text=="New Game","selector immediately updates title")
 check(Preferences.new(path).read_choice()=="en","manual language survives new preference instance")
 var records: Array[Dictionary]=[{"manual":false,"legacy":false,"status":"ready","outcome":"active","day":2,"settlement":1,"date":"2026-09-14 UTC"}]
 menu.view.show_records(records)
 service.choose("zh_CN");await frames(3)
 check(menu.view._heading.text=="选择记录","record list stays open and updates language")
 check(menu.view._list.get_child(0).text.contains("第 2 天"),"formatted records are translated")
 var options=load("res://presentation/campaign_options.gd").new();root.add_child(options);await frames(3)
 options.get_node("%LanguageSelector").item_selected.emit(3);await frames(3)
 check(service.locale=="en" and menu.view._heading.text=="Load Journey","pause selector shares language preference")
 check(options.music.value==40 and options.effects.value==80,"language does not alter volume")
 check(not service.choose("xx"),"unknown manual language rejected")
 var before=FileAccess.get_file_as_string(path)
 check(not service.choose("xx") and FileAccess.get_file_as_string(path)==before,"invalid selection preserves preference bytes")
 var future=FileAccess.open(path,FileAccess.WRITE);future.store_string("[language]\nversion=99\nchoice=\"zh_CN\"\n");future.close()
 var original=FileAccess.get_file_as_string(path)
 check(not service.choose("zh_TW") and FileAccess.get_file_as_string(path)==original,"unknown preference version preserved; session language still switches")
 check(service.locale=="zh_TW" and service.save_failed,"save failure is exposed while language applies")
 options.queue_free();menu.queue_free();await frames(2)
 DirAccess.remove_absolute(path)
 print("Language scene assertions: %d; failures: %d"%[assertions,failures]);quit(0 if failures==0 else 1)
