"""Original 32-second minor-key bell/analog-pad loop; no sampled recordings."""
from pathlib import Path
import wave
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
def main():
 sr=22050;duration=32;t=np.arange(sr*duration)/sr;mix=np.zeros_like(t)
 def note(midi):return 440*2**((midi-69)/12)
 for bar,root in enumerate([48,44,51,46,48,44,51,46]):
  start=bar*4;local=t-start;env=np.clip(local/.35,0,1)*np.clip((4-local)/.6,0,1)
  env[(local<0)|(local>=4)]=0
  for pitch in [root-12,root,root+7]:
   f=note(pitch);mix+=.07*env*(np.sin(2*np.pi*f*local)+.2*np.sin(2*np.pi*f*2*local))
  for beat,step in enumerate([7,12,15,12,7,3,10,7]):
   local=t-(start+beat*.5);env=np.where(local>=0,np.exp(-np.maximum(local,0)*4)*(1-np.exp(-np.maximum(local,0)*80)),0)
   f=note(root+step);mix+=.14*env*(np.sin(2*np.pi*f*local)+.28*np.sin(2*np.pi*f*3*local))
 mix*=np.minimum(t/.1,1)*np.minimum((duration-t)/.2,1)
 mix*=.4/max(np.max(np.abs(mix)),.001)
 out=ROOT/'art/audio/frontier-music-v001';out.mkdir(parents=True,exist_ok=True)
 with wave.open(str(out/'last-refuge.wav'),'wb') as w:w.setparams((1,2,sr,0,'NONE','not compressed'));w.writeframes((mix*32767).astype('<i2').tobytes())
 (out/'README.md').write_text('Original deterministic composition: last-refuge.wav, 32 seconds, 22050 Hz mono PCM. Minor-key bell arpeggios over synthesized pads. Generated by tools/generate_frontier_music.py; no samples, recordings or third-party music. Native playback loop is enabled by CampaignAudio.\n')
if __name__=='__main__':main()
